### ISSUE TITLE
  java.lang.UnsatisfiedLinkError: dtxjpi  when running maps in DataStage

### ISSUE THREAD

**Issue by ibmwtx** [ibmwtx/DataStage-Integration#1]
While we are working with WTX for InfoSphere Datastage that executes on top of the Java Integration stage, we could see some issues
Error 1:
hipaa_837p_5010​_flat,0: java.lang.Unsat​isfiedLinkError​: dtxjpi (The specified procedure could not be found. )
at java.lang.Class​Loader.loadLibr​aryWithPath (ClassLoader.ja​va: 1542)
at java.lang.Class​Loader.loadLibr​aryWithClassLoa​der (ClassLoader.ja​va: 1506)
at java.lang.Syste​m.loadLibrary (System.java: 562)

After setting Jvm argument :

-Djava.library.​path="C:\IBM\We​bSphere Transformation Extender 8.4.1\dtxjpi.dl​l"
facing with below error,
Error 2 :
hipaa_837p_5010​_flat: java.lang.NoCla​ssDefFoundError​: com.ascential.e​2.connector.CC_​ConnectorLibrar​y (initialization failure)
at java.lang.J9VMI​nternals.initia​lizationAlready​Failed (J9VMInternals.​java: 121)

hipaa_837p_5010​_flat: Java runtime exception occurred: java.lang.NoCla​ssDefFoundError​: com.ascential.e​2.connector.CC_​ConnectorLibrar​y (initialization failure) (java.lang.J9VM​Internals::init​ializationAlrea​dyFailed, file J9VMInternals.j​ava, line 121)

**Comment by ibmwtx** [comment]
PATH or LIBPATH environment variable must include the WebSphere TX installation. In Datastage, there should be a batch file. 

For Unix Environment (WTX setup scrips is present under WTX install Directory named as setup )

a) Edit dsenv to add setup script and restart the server on linux

or 

b) Log in to the engine tier computer as the IBM® InfoSphere DataStage® administrator 
    \* First invoke the WTX Setup script  (. ./setup) and then
    \*  cd $DSHOME
      . ./dsenv  ( $DSHOME is the name of the engine directory. The default directory is /opt/IBM/InformationServer/Server/DSEngine.)
- Start the DS engine

For Windows Environment :  Add WTX Install Directory to System PATH

**Comment by Girish93** [comment]
Hi 
I have taken the WebSphere TX installation path and included in the environment variable , and also
will u tell about the batch file which you mentioned.
And the configuration of the system am using is (Windows).
You asked us to invoke the WTX Setup script (. ./setup) , So where exactly i will find it..

**Comment by ibmwtx** [comment]
On Windows , just adding the path to System Environment is sufficient.  The setup scripts is for UNIX integration only.

**Comment by ibmwtx** [comment]
Can you provide what Java version are you running on ? IBM Java  or Solaris ? What version of WTX and 32 or 64 ?

**Comment by Girish93** [comment]
we have tried with both WTX 32-bit and 64-bit with respective IBM Java 
and am working with Java (JDK Version is 1.7.0_55)

About path I have included the WebSphere TX installation path in System Environment.and facing the error has 
hipaa_837p_5010_flat,0: java.lang.UnsatisfiedLinkError: dtxjpi(The specified procedure could not be found. )
at java.lang.ClassLoader.loadLibraryWithPath (ClassLoader.java: 1542)
at java.lang.ClassLoader.loadLibraryWithClassLoader (ClassLoader.java: 1506)
at java.lang.System.loadLibrary (System.java: 562)

**Comment by ggvsivakumar** [comment]
Hey,
Well I have been facing same issue. while locating the WTX installation path in System Environment Path variable. I'm attaching the log with respective to the issue. please look into it.
[log.txt](https://github.com/ibmwtx/DataStage-Integration/files/152470/log.txt)
